package prof.db.sql.seeders

import org.jetbrains.exposed.sql.selectAll
import prof.Requests.CreateCarRequest
import prof.db.sql.SqlCarRepository
import prof.db.sql.SqlEntityAttributeRepository
import prof.db.sql.migrations.Cars
import prof.enums.PowerSourceTypeEnum

class CarSeeder(
     val carRepository: SqlCarRepository = SqlCarRepository(
        entityAttributeRepo = SqlEntityAttributeRepository()
    )
){
    suspend fun run() {
        if (Cars.selectAll().empty()) {
            println("🚗🚗🚗 CarSeeder start...")
            val cars = listOf(
                CreateCarRequest(
                    userId = 1,
                    make = "Tesla",
                    model = "Model 3",
                    price = 48990f,
                    pickupLocation = "Amsterdam",
                    category = "Sedan",
                    powerSourceType = PowerSourceTypeEnum.BEV,
                    color = "Wit",
                    engineType = "Dual Motor",
                    enginePower = "283 kW",
                    fuelType = "Electric",
                    transmission = "Automatic",
                    interiorType = "Leder",
                    interiorColor = "Zwart",
                    exteriorType = "Metallic",
                    exteriorFinish = "Gloss",
                    wheelSize = "18 inch",
                    wheelType = "Alloy",
                    seats = 5,
                    doors = 4,
                    modelYear = 2024,
                    licensePlate = "EV-123-T",
                    mileage = 12000,
                    vinNumber = "5YJ3E1EA7KF123456",
                    tradeName = "Tesla Model 3",
                    bpm = 0f,
                    curbWeight = 1760,
                    maxWeight = 2230,
                    firstRegistrationDate = "2024-03-12",
                    bookingCost = "50",
                    costPerKilometer = 0.25,
                    deposit = "500"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "Volkswagen",
                    model = "Golf",
                    price = 28990f,
                    pickupLocation = "Rotterdam",
                    category = "Hatchback",
                    powerSourceType = PowerSourceTypeEnum.ICE,
                    color = "Blauw",
                    engineType = "1.5 TSI",
                    enginePower = "110 kW",
                    fuelType = "Benzine",
                    transmission = "Manual",
                    interiorType = "Stof",
                    interiorColor = "Grijs",
                    exteriorType = "Standard",
                    exteriorFinish = "Mat",
                    wheelSize = "17 inch",
                    wheelType = "Alloy",
                    seats = 5,
                    doors = 5,
                    modelYear = 2022,
                    licensePlate = "GK-456-R",
                    mileage = 32000,
                    vinNumber = "WVWZZZ1KZMW123456",
                    tradeName = "Golf 8",
                    bpm = 1200f,
                    curbWeight = 1320,
                    maxWeight = 1820,
                    firstRegistrationDate = "2022-05-20",
                    bookingCost = "30",
                    costPerKilometer = 0.20,
                    deposit = "400"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "BMW",
                    model = "i4",
                    price = 65900f,
                    pickupLocation = "Utrecht",
                    category = "Coupe",
                    powerSourceType = PowerSourceTypeEnum.BEV,
                    color = "Zilver",
                    engineType = "eDrive40",
                    enginePower = "250 kW",
                    fuelType = "Electric",
                    transmission = "Automatic",
                    interiorType = "Leder",
                    interiorColor = "Beige",
                    exteriorType = "Sport",
                    exteriorFinish = "Gloss",
                    wheelSize = "19 inch",
                    wheelType = "Alloy",
                    seats = 5,
                    doors = 4,
                    modelYear = 2023,
                    licensePlate = "EV-789-B",
                    mileage = 8000,
                    vinNumber = "WBY33AW02PFR12345",
                    tradeName = "BMW i4 eDrive40",
                    bpm = 0f,
                    curbWeight = 2050,
                    maxWeight = 2500,
                    firstRegistrationDate = "2023-06-15",
                    bookingCost = "60",
                    costPerKilometer = 0.30,
                    deposit = "600"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "Toyota",
                    model = "Corolla Hybrid",
                    price = 29900f,
                    pickupLocation = "Den Haag",
                    category = "Sedan",
                    powerSourceType = PowerSourceTypeEnum.HEV,
                    color = "Rood",
                    engineType = "1.8 Hybrid",
                    enginePower = "90 kW",
                    fuelType = "Hybrid",
                    transmission = "CVT",
                    interiorType = "Stof",
                    interiorColor = "Zwart",
                    exteriorType = "Standard",
                    exteriorFinish = "Gloss",
                    wheelSize = "16 inch",
                    wheelType = "Steel",
                    seats = 5,
                    doors = 4,
                    modelYear = 2023,
                    licensePlate = "HY-234-T",
                    mileage = 15000,
                    vinNumber = "JTDBR32E720123456",
                    tradeName = "Corolla Hybrid",
                    bpm = 700f,
                    curbWeight = 1390,
                    maxWeight = 1835,
                    firstRegistrationDate = "2023-02-18",
                    bookingCost = "35",
                    costPerKilometer = 0.22,
                    deposit = "400"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "Mercedes-Benz",
                    model = "EQS 450+",
                    price = 119900f,
                    pickupLocation = "Eindhoven",
                    category = "Luxury",
                    powerSourceType = PowerSourceTypeEnum.BEV,
                    color = "Zwart",
                    engineType = "RWD",
                    enginePower = "265 kW",
                    fuelType = "Electric",
                    transmission = "Automatic",
                    interiorType = "Leder",
                    interiorColor = "Wit",
                    exteriorType = "Luxury",
                    exteriorFinish = "Gloss",
                    wheelSize = "20 inch",
                    wheelType = "Alloy",
                    seats = 5,
                    doors = 4,
                    modelYear = 2024,
                    licensePlate = "EQ-999-L",
                    mileage = 5000,
                    vinNumber = "W1K29567812345678",
                    tradeName = "EQS 450+",
                    bpm = 0f,
                    curbWeight = 2480,
                    maxWeight = 2950,
                    firstRegistrationDate = "2024-04-22",
                    bookingCost = "100",
                    costPerKilometer = 0.40,
                    deposit = "1000"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "Ford",
                    model = "Focus",
                    price = 24900f,
                    pickupLocation = "Tilburg",
                    category = "Hatchback",
                    powerSourceType = PowerSourceTypeEnum.ICE,
                    color = "Zilvergrijs",
                    engineType = "1.0 EcoBoost",
                    enginePower = "92 kW",
                    fuelType = "Benzine",
                    transmission = "Manual",
                    interiorType = "Stof",
                    interiorColor = "Zwart",
                    exteriorType = "Standard",
                    exteriorFinish = "Mat",
                    wheelSize = "16 inch",
                    wheelType = "Steel",
                    seats = 5,
                    doors = 5,
                    modelYear = 2021,
                    licensePlate = "FO-321-T",
                    mileage = 45000,
                    vinNumber = "WF0AXXWPMAMR12345",
                    tradeName = "Focus Trend",
                    bpm = 900f,
                    curbWeight = 1270,
                    maxWeight = 1780,
                    firstRegistrationDate = "2021-10-12",
                    bookingCost = "25",
                    costPerKilometer = 0.18,
                    deposit = "300"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "Volvo",
                    model = "XC60 Recharge",
                    price = 68900f,
                    pickupLocation = "Zwolle",
                    category = "SUV",
                    powerSourceType = PowerSourceTypeEnum.HEV,
                    color = "Wit",
                    engineType = "T6 Plug-in Hybrid",
                    enginePower = "250 kW",
                    fuelType = "Hybrid",
                    transmission = "Automatic",
                    interiorType = "Leder",
                    interiorColor = "Beige",
                    exteriorType = "SUV",
                    exteriorFinish = "Gloss",
                    wheelSize = "19 inch",
                    wheelType = "Alloy",
                    seats = 5,
                    doors = 5,
                    modelYear = 2023,
                    licensePlate = "XC-456-T",
                    mileage = 9000,
                    vinNumber = "YV1UZBMU0R1234567",
                    tradeName = "XC60 Recharge T6",
                    bpm = 0f,
                    curbWeight = 2140,
                    maxWeight = 2600,
                    firstRegistrationDate = "2023-09-10",
                    bookingCost = "70",
                    costPerKilometer = 0.28,
                    deposit = "700"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "Audi",
                    model = "A3 Sportback",
                    price = 34900f,
                    pickupLocation = "Nijmegen",
                    category = "Hatchback",
                    powerSourceType = PowerSourceTypeEnum.ICE,
                    color = "Zwart",
                    engineType = "2.0 TDI",
                    enginePower = "110 kW",
                    fuelType = "Diesel",
                    transmission = "Automatic",
                    interiorType = "Leder",
                    interiorColor = "Zwart",
                    exteriorType = "Sport",
                    exteriorFinish = "Gloss",
                    wheelSize = "18 inch",
                    wheelType = "Alloy",
                    seats = 5,
                    doors = 5,
                    modelYear = 2022,
                    licensePlate = "A3-567-D",
                    mileage = 27000,
                    vinNumber = "WAUZZZ8V0MA123456",
                    tradeName = "A3 Sportback TDI",
                    bpm = 1500f,
                    curbWeight = 1395,
                    maxWeight = 1850,
                    firstRegistrationDate = "2022-07-01",
                    bookingCost = "40",
                    costPerKilometer = 0.23,
                    deposit = "450"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "Peugeot",
                    model = "208",
                    price = 21900f,
                    pickupLocation = "Leeuwarden",
                    category = "Compact",
                    powerSourceType = PowerSourceTypeEnum.ICE,
                    color = "Geel",
                    engineType = "1.2 PureTech",
                    enginePower = "75 kW",
                    fuelType = "Benzine",
                    transmission = "Manual",
                    interiorType = "Stof",
                    interiorColor = "Zwart",
                    exteriorType = "Standard",
                    exteriorFinish = "Gloss",
                    wheelSize = "16 inch",
                    wheelType = "Steel",
                    seats = 5,
                    doors = 5,
                    modelYear = 2021,
                    licensePlate = "PG-345-G",
                    mileage = 38000,
                    vinNumber = "VF3CCCFZPJR123456",
                    tradeName = "Peugeot 208",
                    bpm = 800f,
                    curbWeight = 1160,
                    maxWeight = 1600,
                    firstRegistrationDate = "2021-08-09",
                    bookingCost = "25",
                    costPerKilometer = 0.17,
                    deposit = "300"
                ),
                CreateCarRequest(
                    userId = 1,
                    make = "Hyundai",
                    model = "Kona Electric",
                    price = 37900f,
                    pickupLocation = "Groningen",
                    category = "SUV",
                    powerSourceType = PowerSourceTypeEnum.BEV,
                    color = "Grijs",
                    engineType = "EV 64 kWh",
                    enginePower = "150 kW",
                    fuelType = "Electric",
                    transmission = "Automatic",
                    interiorType = "Stof",
                    interiorColor = "Zwart",
                    exteriorType = "Standard",
                    exteriorFinish = "Gloss",
                    wheelSize = "17 inch",
                    wheelType = "Alloy",
                    seats = 5,
                    doors = 5,
                    modelYear = 2024,
                    licensePlate = "EV-654-H",
                    mileage = 6000,
                    vinNumber = "KMHK281HUMU123456",
                    tradeName = "Kona Electric",
                    bpm = 0f,
                    curbWeight = 1680,
                    maxWeight = 2170,
                    firstRegistrationDate = "2024-05-17",
                    bookingCost = "40",
                    costPerKilometer = 0.24,
                    deposit = "500"
                )
            )

            cars.forEach {
                try {
                    val created = carRepository.create(it)
                    println("✅ Car toegevoegd: ${created.id}")
                } catch (e: Exception) {
                    println("⚠️ Can car ${it.model} not create: ${e.message}")
                }
            }

            println("✅ CarSeeder ready.")
        }
    }
}